# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: PIAT Arthur
title: PhD student in electrical System modeling and optimization
email: piat.arthur67@gmail.com
website: www.github.com/Pimss

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  Pimss
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: arthur-piat-a97229100
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/picture.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently a PhD student working in the fields of high frequency predictive modeling of electrical systems. This cover Electromagnetic Compatibility (EMC) and global electrical system modeling and optimization.
  Before this I was a research engineer working in Multidisciplinary Design Optimization of electrical system. I had had various work experience in very different companies: small companies for a more diverse and operational activity and flexible environments, big companies with large amount of know-how in aeronautics with numerical simulations and various levels of computational requirements. 
  This broad background always gives me ideas for new projects that I love to share on github.
  Feel free to contact me over one of my projects or one of my publications, I'll be happy to discuss it!


content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IRT Saint Exupéry
        link: https://www.irt-saintexupery.com
        link_text: IRT Saint Exupéry
        sub_title: PhD student
        caption: 2021 - now
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Developing tools and methodologies to predict by simulations the high frequency behavior of electric motors to increase the power density of electrical systems for electric aircraft (EMC, dV/dt, overvoltage, ...).
          Intertwine Finite Element modeling software with Spice-like approaches to simulate complex systems and predict system impedance.
          Use predictive modeling, design of experiments and uncertainties to target efficient design parameters and improve overall system performances.
          Design experiments and prototypes allowing performing various test campaigns, validating simulation approaches.
       
      - layout: left
        title:  INSA Toulouse
        link: https://www.insa-toulouse.fr/en/index.html
        link_text: INSA Toulouse
        sub_title: Part time Teacher
        caption: 2022 - now
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Teach lectures on how to size DC actuators and simple AC systems.
          Guide students during various projects including FEM simulation and 1D temporal validation using various software.
          Design evaluation to assess student level to the provided lesson.
          
      - layout: left
        title: Liebherr Aerospace
        link: https://www.liebherr.com/en/fra/products/aerospace-and-transportation-systems/aerospace/aerospace.html
        link_text: liebherr.com/aerospace
        sub_title: Research engineer
        caption: 2019 - 2021
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Translating and coding state-of-the-art predictive codes for FlyingCap and Fullbridge inverter topologies covering system behavior and EMC pertubations prediction.
          Formatting sizing methodologies to allows optimization algorithms to size and optimize EMC passive filtering devices
          Use Multidiscilinary Design Optimization methods to compute system trade-off using predictive approaches.
          Validate simulation approaches on a 15kVA and 50kVA test benches and ensure EMC regulation compliance.
          
          
      - layout: left
        title: IRT Saint Exupéry
        link: https://www.irt-saintexupery.com
        link_text: IRT Saint Exupéry
        sub_title: Research engineer
        caption: 2018 - 2019
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Use MDO tools to simulate electrical models to predict system mass and reduce overall weight. 
          Interact with various domains expert to validate optimization results and confirm key design improvement.
          Automate integration of MATLAB codes within Python optimization routine allowing solving coupled disciplines.
      - layout: left
        title: Digital Product Simulation
        link: https://dps-fr.com/
        link_text: DPS
        sub_title: GUI developer
        caption:  February 2017 - July 2017
        #quote: >
        description: | # this will include new lines to allow paragraphs
          6-month internship in a SME company.
          Developed a MATLAB-Java hybrid Graphical User Interface to access a Sequel Database (SQL).
          Used Oriented Object programing in MATLAB to create a composite pattern local database allowing loading and updating a remote SQL. 
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ENS Paris-Saclay
        caption: 2021 - now
        sub_title: PhD student in high frequency modeling of electrical motor
        description: | # this will include new lines to allow paragraphs
          PhD thesis in partnership with IRT Saint Exupéry. 
          Use predictive approaches to simulate HF motor impedances.
          
      - layout: left
        title: INSA Toulouse 
        caption: 2015 - 2017
        sub_title: System Engineering
        description: Engineering diploma in System Engineering. Core course were global temporal multiphysic simulation, sizing of power trains (electric, hydraulic, mechanic) and overall system optimization.
        
      - layout: left
        title: INSA Toulouse 
        caption: 2012 - 2015
        sub_title: Mechanical Engineering
        # quote: >
        description: | # this will include new lines to allow paragraphs
          Three years in engineering school. These were dedicated to core courses before the selection of a specialty in the second year and final speciality.    

      - layout: left
        title: Lycée Durzy
        caption: 2009 - 2012
        #sub_title: 
        #quote: >
        #  General engineering is a very French concept where is taught a bit of everything, or as some critics might say: a bit of nothing.
        description: | # this will include new lines to allow paragraphs
          Baccalauréat (equivalent to A-levels) in science and engineering with honors.

  - title: Skills
    layout: text
    content: | #test
      * **Languages**: English (Fluent), French (Native), Spanish (Conversational)
      * **Statistics**: Optimization, Gradient methods, Uncertainty quantification, Numerical solver, Graph Theory.
      * **Programming**: Python, MATLAB, Simulink, C, Git
      * **Software tools**: Eclipse, Anaconda, FEMM, LTSpice, Dymola

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
     - layout: left
        title: January 2024
        sub_title: Journal article
        caption: Science and Technology for Energy Transition
        #quote: >
        description: | # this will include new lines to allow paragraphs
          **Joint work with Sami HLIOUI, Pierre-Etienne LEVY, François COSTA and Sébastien SERPAUD. In random wounded motors, design parameters such as the number of wire in parallel by turns and the overall placement of conductor is shown to have a major impact on impedances.
      - layout: left
        title: September 2023
        sub_title: Workshop paper
        caption: EMC Europe 2023
        #quote: >
        description: | # this will include new lines to allow paragraphs
          **Predictive sensitivity analysis of motor's windings HF impedances**. Joint work with Sami HLIOUI, Pierre-Etienne LEVY and François COSTA. Presents successful prediction of winding evolution with regards to design variables, validated on multiple prototypes by measurements.
      - layout: left
        title: June 2023
        sub_title: Workshop paper
        caption: CEM 2023
        #quote: >
        description: | # this will include new lines to allow paragraphs
          **Modélisation des impédances de Mode Commun et Différentiel d'un bobinage statorique, Impact d'une distribution aléatoire des conducteurs dans les encoches**. Joint work with Sami HLIOUI, Pierre-Etienne LEVY and François COSTA. Introduce the problematic of winding arrangement and features few examples of simulation with increasing levels of random winding.

      - layout: left
        title: October 2022
        sub_title: Workshop paper
        caption: CISTEM 2022
        #quote: >
        description: | # this will include new lines to allow paragraphs
          **AC motor impedance HF modeling for designing with windings variability**. Joint work with Pierre-Etienne LEVY, Sami HLIOUI, François COSTA and Sébastien SERPAUD. Presents an approach to generate random windings and compute matching impedances, while giving preliminary simulation results.


      - layout: left
        title: August 2021
        sub_title: Workshop paper
        caption: EPE 2021
        #quote: >
        description: | # this will include new lines to allow paragraphs
          **A Multidisciplinary Design Optimization Approach for EMC Filter Design For More Electric Aircraft Application**. Joint work with Hans H. SATHLER, François GALLARD and Bernardo COUGO. Presents an approach designing EMC filters in interaction with system constraints and reducing the global system mass by taking advanges of interactions.



  - title: Projects
    layout: text
    content: | # this will include new lines to allow paragraphs
      Here is the non-exhaustive list of some personal projects that I worked on:
      - [Networking and types of VPN to allow seamless streaming of a gaming PC or console](https://github.com/williampiat3/ImprovingPSRemotePlay)
      - [Making a photobooth for my brother's wedding](https://github.com/williampiat3/photoBoothQ)
      - Automate and control home appliance sleeping times, minimizing power draw
  - title: Some Extra
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I am not working I like:
      - Brewing all kinds of beers in all kinds of format.
      - Tinkering with Raspberry pis, Arduinos, 3D printing and CNC machining.
      - Biking.
      - Repairing broken electronics and bikes.
  
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
